<a href="https://colab.research.google.com/github/Lalithasri73/cognifyz-task-1-with-restaurent-dataset/blob/main/cognifyz_task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.preprocessing import LabelEncoder

In [34]:
restaurant_data=pd.read_csv(r"Dataset .csv")
restaurant_data

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [35]:
restaurant_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [36]:
columns_to_keep = ['Cuisines', 'Restaurant Name','Average Cost for two']
restaurant_data.drop(restaurant_data.columns.difference(columns_to_keep), axis=1,inplace=True)

In [37]:
restaurant_data

Restaurant Name                          Cuisines  \
0             Le Petit Souffle        French, Japanese, Desserts   
1             Izakaya Kikufuji                          Japanese   
2       Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian   
3                         Ooma                   Japanese, Sushi   
4                  Sambo Kojin                  Japanese, Korean   
...                        ...                               ...   
9546               Naml۱ Gurme                           Turkish   
9547              Ceviz A��ac۱   World Cuisine, Patisserie, Cafe   
9548                     Huqqa            Italian, World Cuisine   
9549               A���k Kahve                   Restaurant Cafe   
9550  Walter's Coffee Roastery                              Cafe   

      Average Cost for two  
0                     1100  
1                     1200  
2                     4000  
3                     1500  
4                     1500  
...                    ...  
9546                    80  
9547                   105  
9548                   170  
9549                   120  
9550                    55  

[9551 rows x 3 columns]

In [38]:
restaurant_data.isnull().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

In [39]:
restaurant_data.dropna(inplace=True)

In [40]:
restaurant_data.isnull().sum()

Restaurant Name         0
Cuisines                0
Average Cost for two    0
dtype: int64

In [41]:
missing_values = restaurant_data.isna().sum()
missing_values_column = restaurant_data['Restaurant Name'].isna().sum()
missing_values_column = restaurant_data['Cuisines'].isna().sum()
missing_values_column = restaurant_data['Average Cost for two'].isna().sum()

In [44]:
label_encoder = LabelEncoder()
restaurant_data['Restaurant Name'] = label_encoder.fit_transform(restaurant_data['Restaurant Name'])
restaurant_data['Cuisines'] = label_encoder.fit_transform(restaurant_data['Cuisines'])

In [45]:
x = restaurant_data[['Restaurant Name', 'Average Cost for two']]
y = restaurant_data['Cuisines']

In [47]:
Scalar = StandardScaler()

Scalar.fit(x)
x = Scalar.transform(x)

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [49]:
model_DT = DecisionTreeClassifier(random_state=10,criterion="gini")
model_DT.fit(x_train,y_train)
y_pred = model_DT.predict(x_test)
print(list(zip(y_test,y_pred)))

[(1173, 1173), (1559, 1154), (1306, 1381), (168, 168), (426, 1406), (1306, 1135), (1306, 1329), (497, 518), (837, 837), (1444, 982), (1329, 1329), (177, 177), (518, 518), (1705, 1705), (1306, 497), (1738, 281), (518, 1559), (186, 177), (331, 331), (986, 986), (753, 549), (1329, 1514), (497, 497), (1329, 1559), (331, 331), (465, 1212), (1262, 1262), (1306, 1329), (1348, 842), (1722, 1329), (6, 259), (1514, 1514), (1329, 518), (557, 1329), (1099, 1099), (828, 1716), (1514, 564), (1275, 1306), (1262, 1306), (214, 1235), (1217, 1216), (307, 307), (1108, 6), (1514, 1514), (1288, 1807), (249, 249), (1514, 1288), (1262, 1306), (497, 546), (1381, 497), (726, 575), (58, 58), (497, 1306), (1514, 758), (186, 177), (1277, 1514), (533, 1358), (1290, 1179), (191, 191), (1520, 1355), (828, 1329), (497, 518), (1348, 530), (1128, 763), (622, 177), (400, 951), (1626, 1626), (1306, 1235), (1530, 177), (1124, 1126), (331, 331), (201, 886), (249, 186), (177, 518), (426, 1391), (1444, 1520), (627, 1552), (1

In [50]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))
accuracy_score=accuracy_score(y_test,y_pred)
print("Accuracy of the model: ",accuracy_score)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         8
           7       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         0
          26   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [51]:
print("Accuracy of the model: ",accuracy_score)

Accuracy of the model:  0.2278679937139864
